version: '3.6'
# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up


services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
#      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net
  selenium:
    image: selenium/standalone-chrome:94.0
    container_name: selenium
    shm_size: 2gb
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
      - 7900:7900
    networks:
      - mongo_net
  crawler:
    build: crawler/
    container_name: crawler
    volumes:
    - ./crawler:/code
    networks:
      - mongo_net
#  my-mongoclient:
#    # build will get tagged with 'image'
#    build: ./my-mongoclient
#    image: fabianlee/my-mongoclient:3.9
#    container_name: my-mongoclient
#    environment:
#      - MONGO_SERVER=my-mongodb
#      - MONGO_INITDB_DATABASE=test
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=admin
#    networks:
#      - mongo_net
#    depends_on:
#      - mongodb

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge