version: '3.6'
# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up


services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
#      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net
    restart: "always"

  selenium:
    image: selenium/standalone-chrome:94.0
    container_name: selenium
    hostname: selenium
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=4
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - mongo_net
    restart: "always"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444" ]
      interval: 30s
      timeout: 10s
      retries: 5

  crawler_cafef:
    image: crawler
    build: crawler/
    container_name: crawler-cafef
    hostname: crawler
    volumes:
      - ./crawler:/code
    command: python crawl_cafef_multiprocess.py --workers 2 --n-page-lookback 40
    networks:
      - mongo_net
    depends_on:
      - selenium
      - mongodb
      - rabbitmq
    restart: "always"

  crawler_vnexpress:
    image: crawler
    build: crawler/
    container_name: crawler-vnexpress
    hostname: crawler
    volumes:
      - ./crawler:/code
    command: python crawl_vnexpress_multiprocess.py --workers 2 --n-page-lookback 3
    networks:
      - mongo_net
    depends_on:
      - selenium
      - mongodb
      - rabbitmq
    restart: "always"

  processing:
    image: processing
    build: processing/
    container_name: processing
    hostname: processing
    volumes:
      - ./processing:/code
    command: sh run_all.sh
    networks:
      - mongo_net
    depends_on:
      - mongodb
      - elasticsearch
      - rabbitmq
    restart: "always"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - SPARK_MASTER=spark://master:7077
      - MASTER=spark://master:7077
    ports:
      - 15672:15672
      - 5672:5672
    restart: "always"
    networks:
      - mongo_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - mongo_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.3.2'
    container_name: kibana
    hostname: kibana
    environment:
      - "SERVER_NAME=kibana.local"
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "XPACK_SECURITY_ENABLED=false"
    ports:
      - 5601:5601
    networks:
      - mongo_net
    depends_on:
      - elasticsearch
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge

# https://github.com/big-data-europe/docker-zeppelin/blob/master/docker-compose.yml
